#!/usr/bin/env bash
#Displays a list of currently running processes

# Use 'ps' command to list all processes, including those without a TTY, and display user-oriented format
ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,comm --forest
