#!/usr/bin/env bash
# Initialize a counter variable
count=1

# Using a while loop to display "Best School" 10 times
while [ $count -le 10 ]; do
    if [ $count -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((count++))
done
