#!/usr/bin/env bash
#initializes count

counter=1

#loops from 1 to 10 and displays different messages
while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]
    then
        echo "Bad luck"
    elif [ $counter -eq 8 ]
    then
        echo "Good luck"
    else
        echo "Best School"
    fi

    ((counter++))
done
